### ISSUE TITLE
when post : getOutputStream() has already been called for this response

### ISSUE THREAD

**Issue by xiaomanzijia** [Raysmond/SpringBlog#27]
Caused by: java.lang.IllegalStateException: getOutputStream() has already been called for this response
	at org.apache.catalina.connector.Response.getWriter(Response.java:625) ~[tomcat-embed-core-8.5.27.jar:8.5.27]
	at org.apache.catalina.connector.ResponseFacade.getWriter(ResponseFacade.java:211) ~[tomcat-embed-core-8.5.27.jar:8.5.27]

**Comment by grayFinger** [comment]
这个问题解决了吗
